language: java
jdk:
  - openjdk6
before_install:
  - wget http://dl.google.com/android/android-sdk_r21.1-linux.tgz
  - tar -zxf android-sdk_r21.1-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter 1,2,9 --no-ui --force --all